Fiap.Web.FarmaciaEficiente/Models/Posto.cs
using Fiap.Web.FarmaciaEficiente.Models.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fiap.Web.FarmaciaEficiente.Models
{
    [Table("Posto")]
    public class Posto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PostoId { get; set; }


        [StringLength(50, MinimumLength = 1, ErrorMessage = "O nome do posto de saúde deve ter entre 1 e 50 caracteres")]
        [Required(ErrorMessage = "Nome é obrigatório")]
        public string? Nome { get; set; }

        [StringLength(50, MinimumLength = 1, ErrorMessage = "A descrição do posto de saúde deve ter entre 1 e 50 caracteres")]
        [Required(ErrorMessage = "Descrição é obrigatória")]
        public string? Descricao { get; set; }

        /*"OneToOne"*/
        [Required(ErrorMessage = "Endereco é obrigatório")]
        public Endereco? Endereco { get; set; }

        [Required(ErrorMessage = "Status é obrigatório")]
        [EnumDataType(typeof(StatusEnum))]
        public StatusEnum Status { get; set; } = StatusEnum.ATIVO;
    }
}

Fiap.Web.FarmaciaEficiente/ViewModels/PostoViewModel.cs
using Fiap.Web.FarmaciaEficiente.Models;
using Fiap.Web.FarmaciaEficiente.Models.Enum;

namespace Fiap.Web.FarmaciaEficiente.ViewModels
{
    public class PostoViewModel
    {
        public int PostoId { get; set; }
        public string? Nome { get; set; }
        public string? Descricao { get; set; }
        public Endereco? Endereco { get; set; }
        public Estoque Estoque { get; set; }
        public List<MedicamentoViewModel>? Medicamentos { get; set; }
        public int QuantidadeMedicamentos { get; set; }
        public int ReturnUrl { get; set; }
        public StatusEnum Status { get; set; }
    }


}

Fiap.Web.FarmaciaEficiente/Controllers/EstoqueController.cs
using Fiap.Web.FarmaciaEficiente.Models;
using Fiap.Web.FarmaciaEficiente.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Fiap.Web.FarmaciaEficiente.ViewModels;

using Microsoft.AspNetCore.Mvc;

using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Web.FarmaciaEficiente.Controllers
{
    [Authorize]
    [TypeFilter(typeof(FiltroAuthorization))]
    [Route("dashboard/estoque")]
    public class EstoqueController : Controller
    {
        private FarmaciaContext _context;

        public EstoqueController(FarmaciaContext context)
        {
            _context = context;
        }

        private Usuario GetUsuarioFromHttpContext()
        {
            return HttpContext.Items["Usuario"] as Usuario;
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create(int postoId)
        {
            ViewData["Usuario"] = GetUsuarioFromHttpContext();
            var posto = _context.Postos.Include(p => p.Endereco).FirstOrDefault(p => p.PostoId == postoId);

            if (posto == null)
            {
                return NotFound();
            }


            var medicamentos = _context.Medicamentos.Where(e => e.Status == Models.Enum.StatusEnum.ATIVO).ToList();
            var viewModel = new AddEstoqueViewModel
            {
                Posto = posto,
                MedicamentosDisponiveis = medicamentos
            };

         

            return View(viewModel);
        }

        [HttpPost]
        [Route("create")]
        public IActionResult Create(AddEstoqueViewModel model)
        {
            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            var medicamento = _context.Medicamentos.FirstOrDefault(p => p.MedicamentoId == model.MedicamentoId);
            var posto = _context.Postos.Include(p => p.Endereco).FirstOrDefault(p => p.PostoId == model.Posto.PostoId);

            var estoque = new Estoque
            {
                Medicamento = medicamento,
                PostoId = model.Posto.PostoId,
                Quantidade = model.Quantidade,
                Status = Models.Enum.StatusEnum.ATIVO
            };

      
            _context.Estoques.Add(estoque);
            _context.SaveChanges();

            TempData["msg"] = "Estoque adicionado com sucesso!";
            TempData["color"] = "success";

            return RedirectToAction("Index", "Posto");
        }

  
    }
}

Fiap.Web.FarmaciaEficiente/Controllers/PostoController.cs
using Fiap.Web.FarmaciaEficiente.Models;
using Fiap.Web.FarmaciaEficiente.Models.Enum;
using Fiap.Web.FarmaciaEficiente.ViewModels;
using Fiap.Web.FarmaciaEficiente.Persistencia;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiap.Web.FarmaciaEficiente.Controllers
{

    [Authorize]
    [TypeFilter(typeof(FiltroAuthorization))]
    [Route("dashboard/posto")]

    public class PostoController : Controller
    {

        private FarmaciaContext _context;

        public PostoController(FarmaciaContext context)
        {
            _context = context;
        }

        private Usuario GetUsuarioFromHttpContext()
        {
            return HttpContext.Items["Usuario"] as Usuario;
        }

        [HttpGet]
        public IActionResult Index(string filter = "posto", string query = "")
        {

            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            var usuario = GetUsuarioFromHttpContext();

            var postos = new List<Posto> { };


            if (filter == "medicamento")
            {
                postos = _context.Estoques
                    .Where(e => e.Medicamento.Nome.Contains(query) && e.Status == StatusEnum.ATIVO)
                    .Select(e => e.Posto)
                    .Distinct()
                    .Include(posto => posto.Endereco)
                    .ToList();
            }
            else if (filter == "posto")
            {
                postos = _context.Postos
                    .Where(p => p.Nome.Contains(query) || string.IsNullOrEmpty(query))
                    .Include(p => p.Endereco)
                    .ToList();

            }




            var postosViewModel = new List<PostoViewModel>();

            foreach (var posto in postos)
            {
                var quantidadeTotalMedicamentos = _context.Estoques
                    .Where(e => e.Posto.PostoId == posto.PostoId && e.Status == StatusEnum.ATIVO)
                    .Sum(e => e.Quantidade);


                var postoViewModel = new PostoViewModel
                {
                    PostoId = posto.PostoId,
                    Nome = posto.Nome,
                    Endereco = posto.Endereco,
                    Descricao = posto.Descricao,
                    Status = posto.Status,
                    QuantidadeMedicamentos = quantidadeTotalMedicamentos
                };
                postosViewModel.Add(postoViewModel);



            }

            return View(postosViewModel);
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Create()
        {
            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            return View();

        }


        [HttpPost]
        [Route("create")]
        public IActionResult Create(Posto model)
        {
            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            _context.Postos.Add(model);
            _context.SaveChanges();

            TempData["msg"] = "Posto cadastrado!";
            TempData["color"] = "success";
            return RedirectToAction("index");
        }



        [HttpPost]
        [Route("delete")]
        public IActionResult Delete(int id)
        {

            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            var posto = _context.Postos.Find(id);
            _context.Postos.Remove(posto);
            _context.SaveChanges();
            TempData["msg"] = "Posto removido com sucesso!";
            TempData["color"] = "success";

            return RedirectToAction("Index");
        }


        [HttpPost]
        [Route("changeStatus")]
        public IActionResult ChangeStatus(int id)
        {
            var posto = _context.Postos.Find(id);
            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            posto.Status = (posto.Status == StatusEnum.ATIVO) ? StatusEnum.INATIVO : StatusEnum.ATIVO;
            _context.Postos.Update(posto);
            _context.SaveChanges();

            TempData["msg"] = "Status do posto alterado com sucesso!";
            TempData["color"] = "success";

            return RedirectToAction("Index");
        }



        [HttpGet]
        [Route("update")]
        public IActionResult Update(int id)
        {

            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            var posto = _context.Postos
                            .Include(p => p.Endereco).First(p => p.PostoId == id);
            return View(posto);
        }



        [HttpGet]
        [Route("detail")]
        public IActionResult Detail(int id)
        {

            ViewData["Usuario"] = GetUsuarioFromHttpContext();
            var posto = _context.Postos
            .Include(p => p.Endereco)
            .FirstOrDefault(p => p.PostoId == id);

            if (posto == null)
            {
                return NotFound();
            }



            var medicamentosRelacionados = _context.Estoques
                .Include(e => e.Medicamento)
                .Where(e => e.Posto.PostoId == posto.PostoId)
                .GroupBy(e => e.MedicamentoId)
                .Select(group => new MedicamentoViewModel
                {
                    MedicamentoId = group.Key,
                    Nome = group.First().Medicamento.Nome,
                    Descricao = group.First().Medicamento.Descricao,
                    Status = group.First().Medicamento.Status,
                    Quantidade = group.Sum(e => e.Quantidade),
                    Disponivel = group.Any(e => e.Medicamento.Status == StatusEnum.ATIVO && e.Quantidade > 0)
                }).ToList();

            var quantidadeMedicamentosAtivos = medicamentosRelacionados
                .Count(m => m.Status == StatusEnum.ATIVO);

            var postoViewModel = new PostoViewModel
            {
                PostoId = posto.PostoId,
                Nome = posto.Nome,
                Endereco = posto.Endereco,
                Descricao = posto.Descricao,
                Status = posto.Status,
                Medicamentos = medicamentosRelacionados,
                ReturnUrl = id,
                QuantidadeMedicamentos = quantidadeMedicamentosAtivos,
                
            };

            return View(postoViewModel);
        }


        [HttpPost]
        [Route("update")]
        public IActionResult Update(Posto posto)
        {

            ViewData["Usuario"] = GetUsuarioFromHttpContext();

            _context.Postos.Update(posto);
            _context.SaveChanges();
            TempData["msg"] = "Posto atualizado com sucesso!";
            TempData["color"] = "success";
            return RedirectToAction("index");
        }

    }
}

Fiap.Web.FarmaciaEficiente/Views/Posto/Create.cshtml
@model Posto

@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Postos Cadastro";
}




<form asp-action="create">

    <div class="row">
        <div class="col-lg-10 mx-auto">
            <partial name="_Form" />
            <div class="row px-3">
                <div class="form-outline ml-3  mb-4" id="createAccountButton">
                    <button type="submit" class="btn btn-primary form-control">Cadastrar</button>
                </div>
            </div>
        </div>
    </div>
 
  

</form>

Fiap.Web.FarmaciaEficiente/Views/Posto/Detail.cshtml
@model Fiap.Web.FarmaciaEficiente.ViewModels.PostoViewModel


@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Posto Detalhe";

    var usuario = ViewData["Usuario"] as Usuario;

}

<head>
    <link rel="stylesheet" href="~/dashboard/css/style-posto.css">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" integrity="sha256-3sPp8BkKUE7QyPSl6VfBByBroQbKxKG7tsusY2mhbVY=" crossorigin="anonymous" />
</head>


<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto mb-4">
            <div class="career-search mb-60">
                <alert></alert>


                <div class="career-div p-3">
                    <h4 class="top-c-sep text-white">@Model.Nome</h4>
                </div>
                <div class="career-div-bottom h-100">

                    <div class="row ">

                        <div class="col-8 align-items-center mx-auto">
                            <ul class="p-0 d-md-flex mt-3 flex-wrap text-capitalize ff-open-sans">
                                <li class="mr-md-4 text-black">
                                    <i class="bi bi-geo-alt-fill"></i> @Model.Endereco.Logradouro, @Model.Endereco.Numero, @Model.Endereco.Cidade, @Model.Endereco.Uf - @Model.Endereco.Cep
                                </li>
                                <li class="mr-md-4  text-black">
                                    <i class="bi bi-capsule mr-2"></i> @Model.QuantidadeMedicamentos
                                </li>
                            </ul>
                        </div>

                        <div class="col-4">

                            @if (usuario.TipoUsuario == Fiap.Web.FarmaciaEficiente.Models.Enum.TipoUsuarioEnum.ADMIN)
                            {
                                <div class="d-flex mt-3 float-end">

                                    <a asp-action="Create" asp-controller="Estoque" asp-route-PostoId="@Model.PostoId" class="btn btn-primary px-4 py-2 mb-4">
                                        <i class="bi bi-plus"></i> Cadastrar
                                    </a>
                                </div>
                            }
                        </div>

                    </div>


                    <div class="row">
                        <div class="col-12">
                            <h6>Descrição: @Model.Descricao</h6>
                        </div>
                    </div>



                    @if (@Model.Medicamentos.Count == 0)
                    {
                        <div class="row">
                            <div class="col-12">
                                <div class="text-center">
                                    <p class="">Não há medicamentos</p>
                                </div>
                            </div>
                        </div>

                    }



                    <div class="py-3 mt-3">
                        @foreach (var item in Model.Medicamentos)
                        {

                            <div class="box-medicamentos d-md-flex align-items-center justify-content-between mb-30">
                                <div class="job-left my-4 d-md-flex align-items-center flex-wrap">

                                    <div class="job-content" style="cursor: pointer">
                                        <h5 class="text-center text-md-left">@item.Nome</h5>
                                        <ul class="p-0 d-md-flex flex-wrap text-capitalize ff-open-sans flex-column">
                                            <li class="mr-md-4">
                                                Descricao: @item.Descricao
                                            </li>
                                            <li class="mr-md-4">
                                                Quantidade: @item.Quantidade
                                            </li>
                                            <li class="mr-md-4" style="color: @(@item.Disponivel ? "#28a745" : "#dc3545");">
                                                @(@item.Disponivel ? "Disponivel" : "Indisponivel")
                                            </li>

                                        </ul>
                                    </div>
                                </div>


                                <div class="job-right my-4 flex-shrink-0 d-flex">
                                    <div class="mx-1">
                                        <a asp-action="create" asp-controller="retirada" asp-route-PostoId="@Model.PostoId" asp-route-MedicamentoId="@item.MedicamentoId" class="btn btn-primary">Pedir retirada</a>
                                    </div>

                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Fiap.Web.FarmaciaEficiente/Views/Posto/Index.cshtml
@model List<Fiap.Web.FarmaciaEficiente.ViewModels.PostoViewModel>


@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Postos";

    var usuario = ViewData["Usuario"] as Usuario;

}

<head>
    <link rel="stylesheet" href="~/dashboard/css/style-posto.css">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" integrity="sha256-3sPp8BkKUE7QyPSl6VfBByBroQbKxKG7tsusY2mhbVY=" crossorigin="anonymous" />
</head>


<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto mb-4">
            <div class="section-title text-center ">
                <h3 class="top-c-sep">Postos Cadastrados</h3>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-10 mx-auto">
            <div class="career-search mb-60">

                <form asp-action="index" method="get" class="career-form mb-60">
                    <div class="row">
                        <div class="col-md-4 col-lg-4 my-3">
                            <div class="input-group position-relative">
                                <input name="query" type="text" class="form-control" placeholder="Digite sua busca" id="keywords">
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4 my-3">
                            <div class="select-container">
                                <select name="filter" required class="custom-select">
                                    <option value="" disabled selected hidden>Tipo de busca</option>
                                    <option value="posto">Posto</option>
                                    <option value="medicamento">Medicamento</option>

                                </select>
                            </div>
                        </div>

                        <div class="col-md-4 col-lg-4 my-3">
                            <button class="btn btn-lg btn-block btn-light btn-custom" id="contact-submit">
                                Buscar
                            </button>
                        </div>
                    </div>
                </form>


                <div class="filter-result">
                    <div class="d-flex align-items-center justify-content-between ">
                        <p class="ff-montserrat">Total de resultados : @Model.Count</p>

                        @if (usuario.TipoUsuario == Fiap.Web.FarmaciaEficiente.Models.Enum.TipoUsuarioEnum.ADMIN)
                        {
                            <div class="row mt-3 justify-content-end">
                                <div class="col-12 d-flex justify-content-end">
                                    <a asp-action="create" class="btn btn-primary px-4 py-2  mb-4 float-end">
                                        <i class="bi bi-plus"></i> Cadastrar
                                    </a>
                                </div>
                            </div>

                        }


                    </div>

                    <alert mensagem="@TempData["msg"]" color="@TempData["color"]"></alert>

                    @foreach (var item in Model)
                    {
                        <div class="job-box d-md-flex align-items-center justify-content-between mb-30" style="background-color: @(item.Status == Fiap.Web.FarmaciaEficiente.Models.Enum.StatusEnum.INATIVO ? "#bdbdbd" : "#fff")">
                            <div class="job-left my-4 d-md-flex align-items-center flex-wrap">

                                <div class="job-content" style="cursor: pointer">
                                    <h5 class="text-center text-md-left">@item.Nome</h5>
                                    <ul class="p-0 d-md-flex flex-wrap text-capitalize ff-open-sans flex-column">
                                        <li class="mr-md-4">
                                            <i class="bi bi-geo-alt-fill"></i> @item.Endereco.Logradouro, @item.Endereco.Numero, @item.Endereco.Cidade, @item.Endereco.Uf - @item.Endereco.Cep
                                        </li>
                                        <li class="mr-md-4">
                                            <i class="bi bi-capsule mr-2"></i> @item.QuantidadeMedicamentos
                                        </li>
                                    </ul>
                                </div>
                            </div>


                            @if (usuario?.TipoUsuario == Fiap.Web.FarmaciaEficiente.Models.Enum.TipoUsuarioEnum.ADMIN)
                            {
                                <div class="job-right my-4 flex-shrink-0 d-flex">
                                    <div class="mx-1">
                                        <a asp-action="detail" asp-route-id="@item.PostoId" class="btn btn-primary">Visualizar</a>
                                    </div>


                                    <div class="dropdown mx-1" >
                                        <button type="button" class="btn btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="bi bi-gear"></i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a asp-action="update" asp-route-id="@item.PostoId" class="dropdown-item">Editar</a>
                                            <a onclick="key.value = @item.PostoId"  class="dropdown-item" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                                Excluir
                                            </a>
                                            <a onclick="postoId.value = @item.PostoId" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#changeStatusModal">
                                                @(item.Status == Fiap.Web.FarmaciaEficiente.Models.Enum.StatusEnum.ATIVO ? "Desativar" : "Ativar")
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Confirmação</h1>
                <button type="button" data-bs-dismiss="modal" class="btn btn-light">
                    <i class="bi bi-x-circle"></i>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente apagar o posto?
            </div>
            <div class="modal-footer">
                <form asp-action="delete">
                    <input type="hidden" name="id" id="key" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="changeStatusModal" tabindex="-1" aria-labelledby="changeStatusModelLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="changeStatusModelLabel">Confirmação</h1>
                <button type="button" data-bs-dismiss="modal" class="btn btn-light">
                    <i class="bi bi-x-circle"></i>
                </button>
            </div>
            <div class="modal-body">
                Deseja realmente alterar o status do posto?
            </div>
            <div class="modal-footer">
                <form asp-action="changeStatus">
                    <input type="hidden" name="id" id="postoId" />
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

Fiap.Web.FarmaciaEficiente/Views/Posto/Update.cshtml
@model Posto
@{
    Layout = "_Dashboard";
    ViewData["Title"] = "Postos Update";
}



<h1>Atualizar o Posto: @Model.Nome</h1>

<form asp-action="update">

    <div class="row">
        <div class="col-lg-10 mx-auto">
            <partial name="_Form" />
            <input asp-for="PostoId" hidden/>
            <div class="row px-3">
                <div class="form-outline ml-3  mb-4" id="createAccountButton">
                    <button type="submit" class="btn btn-primary form-control">Editar</button>
                </div>
            </div>
        </div>
    </div>
</form>

Fiap.Web.FarmaciaEficiente/Views/Posto/_Form.cshtml
@model Posto


<style>
    .nav-pills .nav-link.active {
        background-color: #6e5aa3;
        color: #fff;
    }

    .nav-pills .nav-link:not(.active) {
        background-color: #f0f0f0;
        color: #000;
    }
</style>

<div class="card-body">
    <div class="mb-4 row">
        <ul class="nav nav-pills nav-justified" id="pills-tab" role="tablist">
            <li class="nav-item mx-2" role="presentation">
                <a class="nav-link active" id="pills-infos-tab" data-bs-toggle="pill" href="#pills-infos" role="tab" aria-controls="pills-infos" aria-selected="true">Informações</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link mx-2" id="pills-adress-tab" data-bs-toggle="pill" href="#pills-adress" role="tab" aria-controls="pills-adress" aria-selected="false">Endereço</a>
            </li>
        </ul>
    </div>

    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-infos" role="tabpanel" aria-labelledby="pills-infos-tab">


            <div class="form-outline mb-4">
                <label asp-for="Nome">Nome</label>
                <input required asp-for="Nome" class="form-control" placeholder="Posto Aclimação" />
            </div>

            <div class="form-outline mb-4">
                <label asp-for="Descricao">Descrição</label>
                <input max="50" min="1" required asp-for="Descricao" class="form-control" placeholder="Posto da fiap" />
            </div>



        </div>

        <div class="tab-pane fade" id="pills-adress" role="tabpanel" aria-labelledby="pills-adress-tab">


            <div class="row">
                <div class="form-outline mb-4 col-4">
                    <label asp-for="Endereco.Cep">CEP</label>
                    <input required asp-for="Endereco.Cep" class="form-control" placeholder="041040-222" />
                </div>


                <div class="form-outline mb-4 col-8">
                    <label asp-for="Endereco.Logradouro">Logradouro</label>
                    <input required asp-for="Endereco.Logradouro" class="form-control" placeholder="Av Lins vasconcelos" />
                </div>
            </div>

            <div class="row">
                <div class="form-outline mb-4 col-6">
                    <label asp-for="Endereco.Numero">Numero</label>
                    <input required asp-for="Endereco.Numero" class="form-control" placeholder="1222A" />
                </div>

                <div class="form-outline mb-4 col-6">
                    <label asp-for="Endereco.Bairro">Bairro</label>
                    <input required asp-for="Endereco.Bairro" class="form-control" placeholder="Cambuci" />
                </div>
            </div>

            <div class="row">
                <div class="form-outline mb-4 col-8">
                    <label asp-for="Endereco.Cidade">Cidade</label>
                    <input required asp-for="Endereco.Cidade" class="form-control" placeholder="São paulo" />
                </div>

                <div class="form-outline mb-4 col-4">
                    <label asp-for="Endereco.Uf">UF</label>
                    <input required asp-for="Endereco.Uf" class="form-control" placeholder="SP" />
                </div>
            </div>

            <div class="row">
                <div class="form-outline col-12 mb-4">
                    <label asp-for="Endereco.Complemento">Complemento</label>
                    <input asp-for="Endereco.Complemento" class="form-control" placeholder="Prédio 2 - sala 3" />
                </div>

            </div>

        </div>
    </div>
</div>


@section Scripts {
    <script>
        function nextStep(tabId) {
            var tab = document.getElementById(tabId);
            var pillsTab = new bootstrap.Tab(document.getElementById('pills-tab'));
            pillsTab.show(tab);
        }

        function previousStep(tabId) {
            var tab = document.getElementById(tabId);
            var pillsTab = new bootstrap.Tab(document.getElementById('pills-tab'));
            pillsTab.show(tab);
        }
    </script>
}